### ISSUE TITLE
Display appendix label of Text-node 

### ISSUE THREAD

**Issue by mingtao13595** [vasturiano/3d-force-graph#140] opened 2018-11-14 15:49 UTC
Thanks for a great job, and could you please check the code below?
Many thanks in advance.

It seems that after code executed below:

.nodeThreeObject(node => {
          const sprite = new SpriteText(node.id);
          sprite.color = node.color;
          sprite.textHeight = 8;
          return sprite;
        })

the label cannot be displayed when hovering...

like the below code cannot work.

.nodeLabel(node => `${node.description1}: ${node.description2}`)
.onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)

Thanks for your time.

**Comment by vasturiano** [comment] 2018-11-15 07:31
Closing as duplicate of https://github.com/vasturiano/3d-force-graph/issues/127

**Closed by vasturiano** 2018-11-15 07:31 UTC
Labels: duplicate
