### ISSUE TITLE
How to import all the .js libraries in typescript instead of using <script> tag?

### ISSUE THREAD

**Issue by SherloqueChang** [vasturiano/3d-force-graph#484] opened 2021-08-08 03:26 UTC
In the given example, `.js` files are imported like:
```
<script src="//unpkg.com/react/umd/react.production.min.js"></script>
  <script src="//unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
  <script src="//unpkg.com/babel-standalone"></script>
  <script src="//unpkg.com/three"></script>
  <script src="//unpkg.com/three-spritetext"></script>
```
However, I'd like to apply it to an React+Typescipt project. But I don't know how to deal with this problem.

**Comment by vasturiano** [comment] 2021-08-08 10:43
Duplicate of https://github.com/vasturiano/react-force-graph/issues/312

**Closed by vasturiano** 2021-08-08 10:43 UTC
