### ISSUE TITLE
Question: Is there a way to specify link lengths for individual links?

### ISSUE THREAD

**Issue by sgordon16** [vasturiano/3d-force-graph#349] opened 2020-07-13 19:18 UTC
Is there a way to specify link lengths for individual links in a DAG?
I was able to do something similar with link width by passing a link accessor function to the linkWidth function
`.linkWidth((link) => (maxDepth) - (link.depth* 0.5))`
I would like to be able to do the same thing for the link lengths.
The function dagLevelDistance only lets you pass a number not a link accessor function.

**Comment by vasturiano** [comment] 2020-07-14 06:51
Duplicate of https://github.com/vasturiano/react-force-graph/issues/203

**Closed by vasturiano** 2020-07-14 06:51 UTC
