### ISSUE TITLE
Creating static nodes unaffected by the physics engine?

### ISSUE THREAD

**Issue by cityy** [vasturiano/3d-force-graph#227] opened 2019-09-07 19:31 UTC
Hi! I am attempting to build a graph that is partially linked to a floorplan. To do that I wanted to create a  3d-force-graph-node for each room and place those nodes in the center of each room-mesh by assigning positional values. 
Now I'm wondering if that's actually possible since I can't seem to set nodes to fixed positions: Directly manipulating the nodes' x,y,z values doesn't have any effect and I assume that's because the physics engine handles that stuff.

So the question is: Is it possible to exclude specific nodes from physics calculation? 

I'm setting up the graph with "collision" force and adding the "room-nodes" afterwards. 

Best
Ferdinand

![Project](https://raw.githubusercontent.com/cityy/udk-graph/standorte/public/img/190907_grundriss.jpg)

**Comment by cityy** [comment] 2019-09-08 09:36
I found a way to achieve what I want using .onEngineTick() and re-setting the node positions on every tick so they appear fixed/static. While this seems to work out, it feels more like a hack than an actual solution. If there's any better way to do this, I would be very interested.

**Comment by vasturiano** [comment] 2019-09-08 20:54
@cityy thanks for reaching out. The simplest way to achieve this is to assign `fx`, `fy` and `fz` attributes to you nodes. These coordinates will be interpreted as fixed and are not affected by the force layout engine.

You can also set a subset of these fixed coordinates, say only `fy` and `fz` to fix the `yz` plane but allow free force directed movement within the `x` coordinates.

**Comment by mister-blanket** [comment] 2019-09-28 18:13
I have tried setting a node attribute for fy, however it seems to be overwritten as 'undefined' at some point in the process. It does this in both DAG and non-DAG modes. Is there a specific method for assigning the fx, fy, and fz attributes to get them to stick?

**Comment by vasturiano** [comment] 2019-09-29 21:15
@mister-blanket in principle if you set `f*` attributes on the nodes the framework should not remove them and keep respecting its values. Could you make a minimal example on codepen that reproduces this issue, to help debug further?

**Comment by mister-blanket** [comment] 2019-10-02 00:51
> @mister-blanket in principle if you set `f*` attributes on the nodes the framework should not remove them and keep respecting its values. Could you make a minimal example on codepen that reproduces this issue, to help debug further?

Apologies, I realized what it was. Though I wasn't using DAG mode, I hadn't removed the config method for it and was merely passing an empty string into it. Removing the .dagMode() method allowed me to write to the 'fy' attribute.

**Closed** 2019-11-13 07:16 UTC
