### ISSUE TITLE
linkParticleColor function return value

### ISSUE THREAD

**Issue by Christof93** [vasturiano/3d-force-graph#101] opened 2018-07-25 14:43 UTC
Hi @vasturiano 

Very good work on this library! It looks absolutely stunning and is very easy to use! 

I have this problem that I want to have variable particle color in the links of a network. Somehow this does not seem to work.

I used this function 
```
.linkDirectionalParticleColor(function(link) {
	if (Math.random() > 0.5) {return "blue"}
	else {return "red"}
})
```
Now what happens is, that all the links will have the same particle color. Sometimes blue, sometimes red. I think the last value that is returned determines the color of all the links actually. 

I think this is not the intended behaviour?

**Comment by vasturiano** [comment] 2018-07-25 17:52
@Christof93 thanks for the report! This was caused by a bug in the library which is now fixed. If you pull the latest version (`1.38.1`) you should get the intended behavior. :)

**Closed** 2018-10-01 15:58 UTC
