### ISSUE TITLE
Crash when dragging nodes together with SpriteText

### ISSUE THREAD

**Issue by alierdogan7** [vasturiano/3d-force-graph#681] opened 2024-07-09 14:00 UTC
Hi @vasturiano, 
I render `SpriteText`s with your nice library `threesprite-text` along with `SphereGeometry` in the same `Mesh` object, as you adviced in one of issues in order to display 2D text over nodes. 

```
(node) => {
      const material = new THREE.MeshLambertMaterial({
        color: node !== hoverNode ? "gray" : "red",
        transparent: true,
        opacity: 0.75,
      });

      let geometry = new THREE.SphereGeometry(24, 32, 16);
      const meshObject = new THREE.Mesh(geometry, material);
      if (node.id) {
        const labelText = new SpriteText(node.id!.toString());
        labelText.color = "red";
        labelText.fontWeight = "bold";
        labelText.textHeight = 30;
        labelText.position.set(25, 25, 25);
        meshObject.add(labelText);
      }
      return meshObject;
    }
```

![image](https://github.com/vasturiano/3d-force-graph/assets/10226678/5aba8433-d4d5-4bcb-ab2b-0624170423ff)

It works great, but if I try to drag nodes by clicking the sprite text instead of the sphere object it causes multiple crashes in the internals of ThreeJS library's DragControls as below:

![image](https://github.com/vasturiano/3d-force-graph/assets/10226678/99f26509-5c21-4d19-b570-4c177133f5c4)

I prepared this codesandbox for minimal reproducable example: https://codesandbox.io/p/sandbox/react-force-graph-threesprite-text-6mpzsk

As a workaround I thought disabling the mouse over events on `SpriteText`s so that clicking on texts won't cause a drag event but couldn't find a way to do so. 

Also, if I disable either showing spritetexts or highlighting nodes on hover, the crash goes away.

Do you have any suggestions to prevent the crash?

Thanks for the great library and support!

**Comment by vasturiano** [comment] 2024-10-09 17:12
Duplicate of https://github.com/vasturiano/three-spritetext/issues/47 .

**Closed by vasturiano** 2024-10-09 17:12 UTC
