### ISSUE TITLE
higlight nearby nodes usign postprocessing effects (depth of field effect, lights, fog?)

### ISSUE THREAD

**Issue by SimonDeDeyne** [vasturiano/3d-force-graph#185] opened 2019-03-06 22:33 UTC
I'm curious to hear if anyone has had any success using postprocessing to make nodes in the foreground more visible. I thought about using fog to achieve a depth of field effect, but there might be other ways for example using lights? 

Any ideas or examples would be greatly appreciated!

**Comment by geohuz** [comment] 2020-01-06 07:50
I actually found a way to get the composer work, basically change your /node_modules/3d-force-graph/dist/3d-force-graph.module.js, at line 158 adding postProcessingComposer, like below:

```
var linkedRenderObjsProps = Object.assign.apply(Object, _toConsumableArray(['width', 'height', 'backgroundColor', 'showNavInfo', 'enablePointerInteraction', 'postProcessingComposer'].map(function (p) {
  return _defineProperty({}, p, bindRenderObjs.linkProp(p));
})));
```

and in your code just do this:

```
Graph.postProcessingComposer(composer)
```

I not sure why the composer doesn't get exposed, may be there is a performance issue.

**Comment by vasturiano** [comment] 2020-01-07 00:49
Duplicate of #265.

**Closed by vasturiano** 2020-01-07 00:49 UTC
