### ISSUE TITLE
Text as nodes does not work

### ISSUE THREAD

**Issue by Masrico** [vasturiano/3d-force-graph#51] opened 2018-04-02 18:16 UTC
Hi Vasturiano,

  First of all, really great piece of work on all force graphs here. Thanks a ton. I am trying both force-graph and also 3D one.

  The Text on Node example does not show text any more, can you please check ? 
       https://vasturiano.github.io/3d-force-graph/example/text-nodes/
   
  Actually, my scenario is show text for group nodes, basically these will be source nodes and show sphere or circle for the target nodes and show text label on target node hover. Also wish to hide/show all other nodes except clicked node and its source/targets. I tried to load 10K+ nodes and it loaded pretty faster than expected.

Thanks

**Comment by vasturiano** [comment] 2018-04-03 03:47
Hi @Masrico, thanks for reaching out. If you're referring to the tooltips not being shown in the above example, that's because there is no `.nodeLabel` property set in the example. Adding `.nodeLabel('id')` will bring back the tooltips, but they will be the exact same as the sprite text so it seemed redundant to add them. But it should work, also if you want to display different content on the tooltip, you can just manipulate the attribute of `nodeLabel`.

The same should be true for the other node interaction functions `onNodeHover`/`onNodeClick` which you can use for the functionality you're describing. It's just that that example didn't have those set.

**Comment by Masrico** [comment] 2018-04-03 04:44
Thanks @vasturiano. sorry for not describing it properly. I mean not the tooltip but the node itself as text (showing text instead of sphere for the source nodes and sphere's for the target nodes), this is functioning pretty well in the non-3D example (https://vasturiano.github.io/force-graph/example/text-nodes/). I hope that makes sense.

**Comment by vasturiano** [comment] 2018-04-03 06:44
Hmmm, the 3d text example is working fine for me. Just in case it's a browser thing, can you let me know the browser you're using when it doesn't work?

Reg the unescape, you can add that directly in the accessor functions, probably is not necessary to change the lib internally. Something like: `.nodeLabel(node => unescape(node.name))`

**Comment by Masrico** [comment] 2018-04-03 12:04
Yes, Just checked and It is working fine in Firefox. 
It does not work in Chrome, I am using Chrome Version (65.0.3325.181 (Official Build) (64-bit)). 

Also, the unescape answer was perfect. Thanks.

**Comment by vasturiano** [comment] 2018-04-03 20:32
@Masrico just tried with that exact version of Chrome (on OSX) and it did function properly. Can you describe a bit more how is it failing for you, maybe take a GIF/screenshot? Also, are there any errors in the console? It could also be due to a browser extension that's changing the behavior, could you try with all the extensions disabled?

Glad you got the unescape to work.

**Comment by Masrico** [comment] 2018-04-04 04:41
@vasturiano, I am using on Windows Environment (Windows 7 and Windows 2012 Server) both give me the same issue in chrome version. Please find the screenshot attached.
![image](https://user-images.githubusercontent.com/2494185/38288806-853653de-37f0-11e8-93f6-da3792e9a107.png)

**Comment by Masrico** [comment] 2018-04-06 14:06
Sorry @vasturiano for pushing this. Did you get a chance to check this ?

**Comment by vasturiano** [comment] 2018-04-07 18:06
Hi @Masrico, thanks for reporting this. I've looked into it. I can reproduce the issue in Win7 (Chrome). However, the issue is fixed in the Chrome version in Win10. I have not tested in Win8 so not sure if it works there.
I don't have the bandwidth right now to troubleshoot older versions of browsers/OSes so my best suggestion for now is to either use it a more recent version of Windows, or use other browsers in Win7/8.

Also, I was able to determine that the issue is actually in another module: https://github.com/vasturiano/three-spritetext

**Comment by Masrico** [comment] 2018-04-08 12:36
thanks @vasturiano , will try it on different browsers.

**Comment by Lumivalkoinen** [comment] 2019-01-30 19:51
> ![image](https://user-images.githubusercontent.com/2494185/38288806-853653de-37f0-11e8-93f6-da3792e9a107.png)

Getting the same effect as Masrico's screenshot with the latest Chrome Version 72.0.3626.81 (Official Build) (64-bit) using Win10 Home.

**Comment by ashwinkalyanpur** [comment] 2019-09-16 09:35
Hi Vastutiano,
I am using npm version of sunbrust chart. I am unable to see the text in firefox but it works fine in chrome. Could not find any solution any where

**Closed** 2019-11-13 06:50 UTC
